version: "3.8"
services:
  nginx:
    image: <NGINX_CONTAINER_ECR_URL>
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: <API_CONTAINER_ECR_URL>
    build:
        context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/dev.env
    ports:
      - "5000:5000"
  client:
    image: <CLIENT_CONTAINER_ECR_URL>
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
